version: "3"

services:

  apache:
    image: httpd:latest
    container_name: apache
    hostname: apache
    restart: unless-stopped
    volumes:
      - ./htdocs:/usr/local/apache2/htdocs/

networks:
  default:
      name: $DOCKER_MY_NETWORK
      external: true
