version: "3.7"
services:
  apache:
    image: httpd:latest
    container_name: apache-blog
    hostname: apache-blog
    restart: unless-stopped
    volumes:
      - ./htdocs:/usr/local/apache2/htdocs/
networks:
  default:
      name: caddy_net
      external: true
